---
title: "Entrega 3"
subtitle: "Análisis de datos multivariable"
author:
  - "Marcos Oliva"
  - "Hugo García"
date: 10/02/2023
format: html
lang: ES
---

```{r Setup, include=FALSE}
knitr::opts_chunk$set(echo=FALSE)
library("tidyverse", warn.conflicts = FALSE)
load(url("https://www.causeweb.org/tshs/datasets/ultrarunning.RData"))
```



# Introducción

En las siguientes secciones, vamos a hacer un análisis multivariable sobre el dataset `UltraRunning`, proveniente de la base de datos de [Teaching of Statistics in the Health Sciences](https://www.causeweb.org/tshs/ultra-running).
Para acceder al repositorio de GitHub de esta entrega, haga clic [aquí](https://github.com/MarcosOlivaMunoz/Entrega-3-AD.git).

## Sobre los datos

El dataset contienen los datos de 288 individuos que completaron ultra-maratones de 100 km y a los cuales se le aplicaron una prueba de inteligencia emocional en tres partes (Tripartite-EI).

## Variables

Este dataset tiene 10 variables diferentes, que explicaremos a continuación:

-   `age`: Este es un dato cuantitativo discreto que muestra el año de nacimiento del competidor.
-   `sex`: Este es un dato cualitativo que muestra el sexo de nacimiento del competidor. Pueden ser hombre o mujer, siendo marcados como $1$ y $2$, respectivamente.
-   `pb_surface`: Este es un dato cualitativo que muestra la superficie en la cual los competidores consiguieron su mejor tiempo de la carrera de 100 km. Hay 4 diferentes: *Sendero*, *Pista*, *Carretera* y *Mixto*, siendo marcados como $1$, $2$, $3$ y $4$, respectivamente.
-   `pb_elev`: Este es un dato cuantitativo contínuo que muestra la suma de todos los cambios de elevación positivos a lo largo de toda la carrera en la cual obtenieron su mejor tiempo en metros.
-   `pb100k_time`: Este es un dato cuantitativo discreto que muestra el mejor tiempo del competidor (auto-proclamado) en el formato de hora estándard `hh:mm:ss`.
-   `pb100k_dec`: Este es un dato cuantitativo contínuo que muestra el mejor tiempo del competidor (auto-proclamado) en horas.
-   `avg_km`: Este es un dato cuantitativo contínuo que muestra la distancia media que el competidor corre cada semana (auto-proclamado) en kilómetros.
-   `teique_sf`: Este es un dato cuantitativo discreto que muestra la puntuación en la prueba de inteligencia emocional.
-   `steu_b`: Este es un dato cuantitativo discreto que muestra la puntuación en la prueba de comprensión emocional.
-   `stem_b`: Este es un dato cuantitativo discreto que muestra la puntuación en la prueba de gestión emocional.